variable "env" {}
variable "service_name" {}
variable "vpc_main" {}
variable "alb_group" {}
variable "ecr" {}
variable "execution_role" {}
variable "private_1a" {}
variable "private_1c" {}
variable "ecs_task_group" {}
variable "repository_version" {}