variable "env" {}
variable "service_name" {}
variable "s3_access_key" {}
variable "s3_secret_key" {}
variable "db_url" {}
variable "db_schema" {}
variable "datasource_url" {}
variable "db_username" {}
variable "db_password" {}
variable "db_driver_classname" {}
variable "region" {}
variable "image_path" {}
variable "jwt_secret" {}
variable "jwt_expiration" {}